"""Streamlit Community Cloud entrypoint for the CardioFamily POC.

Embeds the self-contained React production build (streamlit_dist/cardiofamily.html,
generated by `npm run build:streamlit` and committed to the repository). The React
app is trusted repository code; nothing is fetched from external services, and
Streamlit adds no UI of its own around it.
"""

from pathlib import Path

import streamlit as st

APP_HTML = Path(__file__).parent / "streamlit_dist" / "cardiofamily.html"

st.set_page_config(
    page_title="CardioFamily POC · Demonstration",
    page_icon="❤️",
    layout="wide",
    initial_sidebar_state="collapsed",
    menu_items={"Get help": None, "Report a bug": None, "About": None},
)

# Let CardioFamily fill the page: hide Streamlit chrome and padding, and size the
# iframe to the viewport (the React app manages its own scrolling).
st.html(
    """
    <style>
      header[data-testid="stHeader"], [data-testid="stToolbar"], [data-testid="stDecoration"],
      [data-testid="stSidebar"], [data-testid="stSidebarCollapsedControl"], footer { display: none !important; }
      .block-container, [data-testid="stMainBlockContainer"] { padding: 0 !important; max-width: 100% !important; }
      [data-testid="stMain"], [data-testid="stAppViewContainer"] { overflow: hidden !important; }
      [data-testid="stVerticalBlock"] { gap: 0 !important; }
      iframe[title="cardiofamily"], [data-testid="stIFrame"] iframe { height: 100vh !important; display: block; border: 0; }
    </style>
    """
)

if not APP_HTML.is_file():
    st.error("CardioFamily build not found. Run `npm run build:streamlit` and commit streamlit_dist/cardiofamily.html.")
    st.stop()

st.iframe(APP_HTML, height=900)
